app:
  github:
    token: ${GITHUB_TOKEN}
    api-url: https://api.github.com
    base-url: https://github.com/
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    topics:
      notification: notification
  http:
    timeout:
      connect: ${TIMEOUT_CONNECT:2s}
      response: ${TIMEOUT_CONNECT:5s}
    retry:
      max-attempts: ${RETRY_ATTEMPTS:5}
      backoff-millis: ${RETRY_MILLIS:1000}
      status-codes:
        - TOO_MANY_REQUESTS
        - INTERNAL_SERVER_ERROR
        - BAD_GATEWAY
        - SERVICE_UNAVAILABLE
  bot:
    url: ${BOT_URL:http://bot:8081}
  transport:
    type: HTTP

spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://postgres:5432/repo_tracker_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false

management:
  server:
    port: 8101
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  metrics:
    enable:
      http.server.requests: true

server:
  port: 8100

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
